import React from 'react';
import { Accordion, Col, Row } from 'react-bootstrap';
import pic from './hero-sm-1.jpg'

const Blog = () => {
     return (
          <Row className='container my-5 mx-auto py-5'>

               <Col md={6}>
                    <img className='img-fluid w-100' style={{height: '600px'}} src={pic} alt="" />
               </Col>
               <Col md={6}>
               <Accordion defaultActiveKey="0">
  <Accordion.Item eventKey="0">
    <Accordion.Header>
         <h5>Difference between authorization and authentication.</h5>
    </Accordion.Header>
    <Accordion.Body>
         <h6>Authentication: </h6>
         <ol>
              <li>
              Authentication is the checking of identity to provide the access to te system
              </li>
              <li>
              In authentication the user will be verified
              </li>
              <li>
              Authentication is done before authorization
              </li>
       
         </ol>


        
          <h6>Authorization: </h6>
          <ol>
               <li>
               Authorization is what users can and cannot access
               </li>
               <li>
               Authorization verifies whether the access of users are allowed through terms and conditions.
               </li>
               <li>
               It is done after successful authentication
               </li>
          </ol>
    </Accordion.Body>
    <Accordion.Header>
         <h5>Why we are using firebase? What other options do we have to implement authentication?</h5>
    </Accordion.Header>
    <Accordion.Body>
    
          <p>
               The main reasons behind using firebase are:
               Firebase provides plenty of features like,
               Firebase database: It is used to store users data and details.
               Firebase Authentication: We can use the authentication by firebase quite easily.
               Firebase cloud Storage: It is used to store the contents like profile pictures , messages etc which are generated by the users.
               React firebase-hooks which makes authentication much easier and cleaner.     
         </p>   
          <h6>Other alternative of firebase authentication can be:</h6> 
          <ol>
               <li>auth0.com</li>
               <li>okta.com</li>
               <li>Keycloak etc</li>
          </ol> 
       
      </Accordion.Body>
  </Accordion.Item>

  <Accordion.Item eventKey="1">
    <Accordion.Header>
         <h5>What other services does firebase provide other than authentication</h5>
    </Accordion.Header>
    <Accordion.Body>
    <ol>
         <li>
         Parse - Open Source Backend Platform;
         </li>
         <li>
         Back4app - Parse Hosting Platform;
         </li>
         <li>
         Kinvey - Mobile Backend as a Service (mBaaS)
         </li>
         <li>
         Backendless - Mobile Backend and API Services Platform;.
         </li>
         <li>
         Pubnub - Real-time APIs and Global Messaging;
         </li>
         <li>
         Kumulos - App Performance Management;
         </li>
         <li>
         NHost - Accelerates development and provides full control;
         </li>
         <li>
         Amplify JS - Open-source Javascript framework;
         </li>
         <li>
         Heroku - Platform as a service backed by Salesforce.
         </li>
    </ol>
    </Accordion.Body>
  </Accordion.Item>
</Accordion>
               </Col>
            
          </Row>
     );
};

export default Blog;